# fly.toml app configuration file generated for swap-backend on 2025-11-07T21:15:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'swap-backend'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  QDRANT_HOST = 'qdrant.internal'
  QDRANT_PORT = '6333'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
